"""initial schema

Revision ID: 7aa1f61bae8a
Revises: 
Create Date: 2026-07-23 01:10:07.496338
"""
from alembic import op
import sqlalchemy as sa


revision = '7aa1f61bae8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('from_email', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('RECRUITER_OUTREACH', 'INTERVIEW_INVITE', 'ASSIGNMENT', 'REJECTION', 'OFFER', 'FOLLOW_UP_NEEDED', 'JOB_ALERT', 'SPAM', 'OTHER', name='emailcategory'), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=True),
    sa.Column('requires_reply', sa.Boolean(), nullable=False),
    sa.Column('company', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=512), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_thread_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=255), nullable=True),
    sa.Column('posted_date', sa.String(length=64), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'TAILORED', 'APPROVED', 'SUBMITTED', 'REJECTED', name='jobstatus'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_job_source_external')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'TAILORED', 'PENDING_APPROVAL', 'APPROVED', 'SUBMITTED', 'REJECTED', 'SKIPPED', name='applicationstatus'), nullable=False),
    sa.Column('tailored_resume_md', sa.Text(), nullable=True),
    sa.Column('cover_letter_md', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('keywords_used', sa.JSON(), nullable=True),
    sa.Column('approved_by_human', sa.Boolean(), nullable=False),
    sa.Column('human_approved_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=True),
    sa.Column('tone_notes', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('requires_human_rewrite', sa.Boolean(), nullable=False),
    sa.Column('gmail_draft_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('applications')
    op.drop_table('jobs')
    op.drop_table('email_threads')
    op.drop_table('action_log')
    # ### end Alembic commands ###
